
backend:
  host: "the host of the service"
  username: "theusername"
  password: ""
  verifyUrl: "http://call-me-please.local/openendpoint"
script:
  # these are scripts local to the "wolserver" machine

  # this is to shutdown the WOLed machine
  shutdown: "shutdown.sh"
  # this is to start the WOLed machine and it services
  start: "start.sh"
  # this is to stop the WOLed machine's services
  stop: "stop.sh"
service:
  # these are configuration of the wolserver service
  # use generatepwdandsalt.py to calculate these
  password: "<base64 of the salted password>"
  salt: "<base64 of salt>"
  port: 5000
  link: "http://call-me-please.local/"


